name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      releaseID:
        description: 'リリースID。例）release/v21.05.01 の `21.05.01`の部分'
        required: true

jobs:
  CreateBranch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout development
        uses: actions/checkout@v2
      - name: create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release/v${{ github.event.inputs.releaseID }}
          git push origin release/v${{ github.event.inputs.releaseID }}