name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      releaseID:
        description: 'リリースID。例）release/v21.05.01 の `21.05.01`の部分'
        required: true

jobs:
  CreateBranch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout development
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/v${{ github.event.inputs.releaseID }}
          delete-branch: true
          title: Release V${{ github.event.inputs.releaseID }}